id: P009162
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17618
  title: 十三世达赖喇嘛的近侍་土登贡培
  author: ''
  volumes:
    795de977fb9c4560808cdf054aadb930:
      image_group_id: I4PD4642
      title: ''
      volume_number: 1
      total_pages: 166
