id: I1C6467F1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T14:28:43+00:00'
last_modified: '2022-06-08T09:03:47.774982+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17618
  title: 十三世达赖喇嘛的近侍་土登贡培
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    290A:
      image_group_id: I4PD4642
      title: ''
      total_pages: 166
      order: 1
      base_file: 290A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
